[package]
name = "ergoweb"
version = "0.8.0"
authors = ["Ben Beckwith <bnbeckwith@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
ergodox-keymap-parser = { path = "../ergodox-keymap-parser"}
